modLoader="javafml"
loaderVersion="[36,)"
license="Attribution-NonCommercial 3.0 Unported"
issueTrackerURL="https://github.com/Melonslise/Locks/issues"

[[mods]]
modId="locks"
version="3.0.3"
displayName="Locks"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://minecraft.curseforge.com/projects/locks"
logoFile="logo.png"
credits="Huge thanks for the new textures to the following artists on the RLCraft server: Hoonts, Artsy (ydgy); for coding help on MMD: Diesieben07, Choonster, Gigaherz, Draco18s, JamiesWhiteShirt, Shadows, DShadowWolf, Xalcon, DarkCow, KillJoy, Ben, TheRealFarfetchd, JTK222, Cadiboo, Lykrast, Quadraxis, Tterrag, Alexbegt, Desht, McJty, AlcatrazEscapee, V0idWa1k3r, Muramasa, Kashike, Commoble, TheSilkMiner, and others; for sounds: freesound.org"
authors="Melonslise"
description='''
Locks is a small, but unique Minecraft mod that introduces flexible and universal locks which can be dynamically attached to multiple blocks of any kind, including other mods, a fun lock picking mechanic as well as lots of other little, but useful tools and utilities.
'''